name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev libudev-dev lld

      - uses: swatinem/rust-cache@v2
      
      # ADD THIS STEP HERE
      - name: Install ALSA dependencies
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev
        
      - name: Install System Dependencies
        run: sudo apt-get install -y libasound2-dev libudev-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Build
        run: cargo build --verbose
